### ISSUE TITLE
Deep populate not working

### ISSUE THREAD

**Issue by aratcliffe** [Atlantis-Software/sails-hook-blueprints-offshore#2]
Hi, I believe I've followed all the necessary steps to use this module but deep populate is not returning the child models when using RESTful routes. It is working when using the model API directly.

I'm using Sails v0.12.3 with sails-hook-orm-offshore 0.0.3 and sails-hook-blueprints-offshore 0.0.1.

.sailsrc looks like this:

```
{
    "generators": {
        "modules": {}
    },

    "hooks": {
        "blueprints": false,
        "orm": false,
        "pubsub": false
    }
}
```

and in globals.js I have the following config:

```
module.exports.globals = {
  ...
  models: true,
  adapters: true
};
```

Any thoughts what I'm doing wrong?

**Comment by aratcliffe** [comment]
I've found the problem actionUtil.js needs to be modified as described here: https://github.com/balderdashy/waterline/pull/1052#issuecomment-137137350 to support deep population. I'll create a pull request for this.

**Comment by atiertant** [comment]
fixed by https://github.com/Atlantis-Software/sails-hook-blueprints-offshore/pull/3
thanks
