### ISSUE TITLE
[Question] Query by association

### ISSUE THREAD

**Issue by dandanknight** [Atlantis-Software/sails-hook-blueprints-offshore#4]
Hi, I'm looking to replace Waterline with Offshore in my project, as I like the deep populate feature which the lack of has hindered my project for a while. 

My question is, is it possible, preferably via a POST, to filter the results by one of the populated values?

For instance, the data..

````
{
  "first": "Charlotte",
  "last": "Morris",
  "username": "cmorris",
  "id": "5840083850d558ed998022a5",
  "pets": [
    {
      "name": "Missy",
      "colour": "Black and White",
      "type": {
        "name": "Dog",
        "noise": "bark",
        "numLegs": "4",
        "id": "58400bcd2277f0ee9a00c8bd"
      },
      "owner": "5840083850d558ed998022a5",
      "id": "58400ac65f329c989afe0e38"
    },
    {
      "name": "Lottie",
      "colour": "Ginger",
      "type": {
        "name": "Cat",
        "noise": "meow",
        "numLegs": "4",
        "id": "58400bcd2277f0ee9a00c8be"
      },
      "owner": "5840083850d558ed998022a5",
      "id": "58400adb5f329c989afe0e39"
    }
  ]
}
````
...where the Models that exist are User->Pet->Animal

Is it possible to query the user Model filtering by for instance `pets.type.name`?

Something like

````
Users.find()
.populate('pets.type', {'pets.type' : 'Dog'})
.exec(function(err, res){
    // some results containing only users with dogs
}
````

**Comment by atiertant** [comment]
hi, yes this is possible by using this syntax:

```
Users.find({pets: {type : 'Dog'}})
.populate('pets')
.exec(function(err, res){
    // some results containing only users with dogs
}
```

in criteria we use nested object instead of dot notation
(tonly working with exec for now)

**Comment by dandanknight** [comment]
Ah OK, many thanks. Is there a limit to the number of levels it will filter do you know? Also, does the association type make a difference? For instance 1-1, 1-many etc.

**Comment by atiertant** [comment]
@dandanknight there is no number of level limit but it has an impact on performance, every level in criteria use a query from lower level to upper one to find in an array of primaryKey...
