### ISSUE TITLE
PR #3 not made it to NPM

### ISSUE THREAD

**Issue by dandanknight** [Atlantis-Software/sails-hook-blueprints-offshore#5]
Hi, I noticed that the deep populate fix [here](https://github.com/Atlantis-Software/sails-hook-blueprints-offshore/pull/3) hasn't been published to NPM yet. Can it be pushed please? 

Many thanks.

**Comment by atiertant** [comment]
i'm updating all npm, a new release will come soon

**Comment by dandanknight** [comment]
OK no worries, I'll install from Git for now. Thanks again.

**Comment by atiertant** [comment]
@dandanknight i updated all packages:
- sails-hook-orm-offshore
- sails-hook-blueprints-offshore
- sails-hook-pubsub-offshore

**Comment by dandanknight** [comment]
Awesome! Thank you very much :-)
